config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  resources :questions
  resources :interviews
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/interview.rb
class Interview < ActiveRecord::Base
  has_many :responses
  accepts_nested_attributes_for :responses
  belongs_to :survey
  belongs_to :contact
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :interview
  belongs_to :question

  #def self.response_types
  #  %w(TextResponse SelectionResponse)
  #end
end

class TextResponse < Response ;
end
class SelectionResponse < Response ;
end
class FollupTruthResponse < Response ;
end
class FollowupTruthTextReponse < Response ;
end
class FollowupNumberResponse < Response ;
end
class PrivateTextResponse < Response ;
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_filter :authenticate_user!
    before_action :set_interview, only: [:show]

    def new
      @survey = Survey.find(params[:survey_id])
      @interview = Interview.new
      @interview.responses.build
      @questions = Question.where(survey_id: @survey.id)
    end

    def index
      @interviews = Interview.all

    end

    def show

    end

    def create
      @interview = Interview.new(interview_params)

      respond_to do |format|
        if @interview.save
          format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_interview
        @interview = Interview.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def interview_params
        params.require(:interview).permit(:survey_id, responses_attributes: [:selection, :content, :question_id])
      end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update]

  def new
    @question = Question.new
    @surveys = Survey.all
    @response_types = Response.subclasses.map{|x| x.name}
  end

  def index
    @questions = Question.all

  end

  def show

  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @surveys = Survey.all
    @response_types = Response.subclasses.map{|x| x.name}
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:survey_id, :content, :order, :suborder, :response_type)
    end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/interviews/_form.html.erb
<%= @survey.name %>
<%= simple_form_for @interview do |i| %>
  <div class="form-inputs">
  <% @questions.each do |q| %>
    Question <%= q.order %>.<%= q.suborder %> :
    <%= simple_format(q.content) %>
    <%= i.simple_fields_for :responses do |r| %>
      <%= r.input :question_id, as: :hidden, input_html: { value: q.id } %>
      <% if q.response_type.eql? "SelectionResponse" %>
        <%= r.input :selection, input_html: { class: 'answer'} %>
      <% elsif q.response_type.eql? "TextResponse" %>
        <%= r.input :content %>
      <% elsif q.response_type.eql? "FollupTruthResponse" %>
        <%= r.input :content %>
        [if yes]
        <%= r.input :followup_truth %>
      <% elsif q.response_type.eql? "FollowupNumberResponse" %>
        <%= r.input :content %>
        How many? <%= r.input :followup_number %>
      <% elsif q.response_type.eql? "PrivateTextResponse" %>
        <%= r.input :content %>
      <% elsif q.response_type.eql? "FollowupTruthTextResponse" %>
          <%= r.input :content %>
          <%= r.input :followup_truth %>
          <%= r.input :followup_text %>
      <% end %>
    <% end %>
  <% end %>
  </div>
  <div class="form-actions">
    <%= i.button :submit %>
  </div>
<% end %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interviews</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Responses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.id %>
        <td><%= interview.responses.count %></td>
        <td><%= link_to 'Show', interview %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form' %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @interview.id %>
  <% @interview.responses.each do |r| %>
    <%= simple_format(r.question.content) %>
    <% if r.question.response_type.eql? "SelectionResponse" %>
      <%= r.selection %>
    <% elsif r.question.response_type.eql? "TextResponse" %>
      <%= r.content %>
    <% end %>
  <% end %>
</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
  <li><%= link_to 'Surveys', surveys_url %></li>
  <li><%= link_to 'Questions', questions_url %></li>
  <li><%= link_to 'Interviews', interviews_url %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ahs" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ahs" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :order %>
    <%= f.input :suborder %>
    <%= f.input :response_type, collection: @response_types, include_blank: false %>
    <%= f.input :survey_id, collection: @surveys, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Questions</h1>

<%= link_to 'New Question', new_question_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.order %>:<%= question.suborder%></td>
        <td><%= simple_format(question.content) %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order</strong>
  <%= @question.order %>
  <strong>Suborder</strong>
  <%= @question.suborder %>
  <strong>Content:</strong>
  <%= simple_format(@question.content) %>
  <strong>Response Type:</strong>
  <%= @question.response_type %>
</p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %> |
<%= link_to 'New Question', new_question_path %>

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Interview', new_interview_path(:survey_id=>survey.id) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>